# TrshLab - Config
# Edit sparingly. Server restart required.

title: LATHYUSLAB
description: "Tech. Bio. Beyond. Welcome to the next 100 years."
url: "https://trshdesigns.github.io"
baseurl: ""
email: "trshdesigns@outlook.com"

theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title

author:
  name: naica
  bio: "Edge data. Future fragments. Tech-bio stream."

collections:
  investigations:
    output: true
    permalink: /x/:title
  projects:
    output: true
    permalink: /projects/:title

defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
    categories: blog
- scope:
    path: ""
    type: investigations
  values:
    layout: post
    categories: x

plugins:
- jekyll-feed

sass:
  sass_dir: _sass
include:
- assets/css/style.css

# Custom navigation links
navigation:
- title: Home
  url: /
- title: About
  url: /about/
- title: Projects
  url: /projects/
- title: Investigations
  url: /investigations/
