# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site Settings
title: TrshDesigns Lab
description: "A chaotic dive into tech, bio-science, and the edges of thought. Welcome to the next 100 years."
url: "https://trshdesigns.github.io" # Base URL
baseurl: "" # Leave empty for root domain
email: "your-email@example.com" # Add your email if you want

# Build Settings
theme: minima # Using minima as a base, we’ll override with custom CSS
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title # Matches your current post URL structure

# Author Info (Based on TrshDesigns vibe)
author:
  name: "Trsh"
  bio: "Investigating the fringes of tech, bio-science, and what's next. Reflections, ideas, and raw data dumps from the edge of the future."

# Collections (Optional, for organizing investigations)
collections:
  investigations:
    output: true
    permalink: /investigations/:title

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: "blog"
  - scope:
      path: ""
      type: "investigations"
    values:
      layout: "post"
      categories: "investigations"

# Plugins
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
